### ISSUE TITLE
when replying to convo, convo is sometimes removed from convo list

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#346]
we pushed a change recently that handles realtime updates for conversations

now, occasionally, when replying to a conversation, the convo entry from the convo list is removed, but not correctly re-inserted
this causes the convo to disappear until a refresh

mostly affects convos that are already at the top of the convo list

**Comment by chrisdadev13** [comment]
<img width="338" alt="Captura de pantalla 2024-04-27 a la(s) 2 54 32 p  m" src="https://github.com/un/inbox/assets/92900301/291c456c-6082-479d-af48-f998a91f75b3">
<img width="1659" alt="Captura de pantalla 2024-04-27 a la(s) 3 05 04 p  m" src="https://github.com/un/inbox/assets/92900301/444c2b5a-937a-4b07-941c-d778695521c9">
<img width="921" alt="Captura de pantalla 2024-04-27 a la(s) 3 05 33 p  m" src="https://github.com/un/inbox/assets/92900301/fd0bea67-cc21-4c7a-b36b-a2db11c66d8c">

I don't know if this issue is related with that change  you mentioned, but this happened to me when I was trying to reply to a convo. Can I try to work on this?

**Comment by McPizza0** [comment]
seems like an unrelated issue
can you open a new one for these schreenshots

**Comment by McPizza0** [comment]
fixed in react
